spring.application.name=CustomerService
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-polished-feather-b33wrnti-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_z5WXEoeMGY2d
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
